version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: subscription_service_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: subscription_service
    ports:
      - "5460:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: